<a href="https://colab.research.google.com/github/kuberiitb/learnings/blob/master/pytorch/lecture_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learnings from [Abhishek Thakur Pytoch Series](https://www.youtube.com/watch?v=_R-mvKBD5U8&list=PL98nY_tJQXZln8spB5uTZdKN08mYGkOf2&index=1)

In [59]:
import torch 
import numpy as np

In [60]:
torch.cuda.is_available()

True

In [61]:
!nvidia-smi

Thu Feb  3 06:43:54 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P0    26W /  70W |   1332MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Conversion from/to list, Numpy, Pytorch

In [62]:
some_data = [[1,2], 
             [3,4]]
type(some_data)

list

In [63]:
some_data_np_1 = np.array(some_data) # way 1 array
some_data_np_2 = np.asarray(some_data) # way 2 asarray
print(some_data_np_1)
print(some_data_np_2) #same
print(type(some_data_np_1))
print(type(some_data_np_2))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [64]:
some_data_torch = torch.tensor(some_data) # from list to torch
print(type(some_data_torch))
print(some_data_torch)

<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]])


In [65]:
some_data_torch2 = torch.tensor(some_data_np_1) # from numpy to torch way 1
print(some_data_torch2)
print(type(some_data_torch2))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [66]:
some_data_torch3 = torch.from_numpy(some_data_np_1) # from numpy to torch way 2
print(some_data_torch3)
print(type(some_data_torch3))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [67]:
some_data_torch_to_np = np.asarray(some_data_torch) # from torch to np
print(some_data_torch_to_np)
print(type(some_data_torch_to_np))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


## Torch matrix

In [68]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [69]:
my_tensor = torch.rand(3,4)
my_tensor

tensor([[0.0369, 0.7925, 0.9034, 0.7876],
        [0.9311, 0.3457, 0.5577, 0.2953],
        [0.6482, 0.9903, 0.2668, 0.4338]])

In [70]:
my_tensor.dtype

torch.float32

In [71]:
my_tensor.device # in cpu

device(type='cpu')

In [72]:
my_tensor_to_cuda = my_tensor.to("cuda")

In [73]:
print(my_tensor_to_cuda.device) # moved to cuda
print(my_tensor.device) # still in cpu

cuda:0
cpu


In [74]:
my_tensor_to_cuda[:, 1:] # slicing work like numpy array/list

tensor([[0.7925, 0.9034, 0.7876],
        [0.3457, 0.5577, 0.2953],
        [0.9903, 0.2668, 0.4338]], device='cuda:0')

In [120]:
my_tensor = my_tensor_to_cuda # rename for ease

# matrix multiplication

In [76]:
my_tensor.mul(my_tensor)  # elementwise

tensor([[0.0014, 0.6281, 0.8161, 0.6204],
        [0.8669, 0.1195, 0.3111, 0.0872],
        [0.4202, 0.9807, 0.0712, 0.1882]], device='cuda:0')

In [77]:
my_tensor * my_tensor # same thing

tensor([[0.0014, 0.6281, 0.8161, 0.6204],
        [0.8669, 0.1195, 0.3111, 0.0872],
        [0.4202, 0.9807, 0.0712, 0.1882]], device='cuda:0')

In [78]:
my_tensor.matmul(my_tensor) # matrix multiplication 
# fail since  3x4 x 3x4

RuntimeError: ignored

In [79]:
my_tensor.matmul(my_tensor.T) # fail since  3x4 x 4x3 = 3x3

tensor([[2.0659, 1.0448, 1.3915],
        [1.0448, 1.3847, 1.2229],
        [1.3915, 1.2229, 1.6603]], device='cuda:0')

In [80]:
torch.matmul(my_tensor, my_tensor.T ) 

tensor([[2.0659, 1.0448, 1.3915],
        [1.0448, 1.3847, 1.2229],
        [1.3915, 1.2229, 1.6603]], device='cuda:0')

In [81]:
my_tensor @ my_tensor.T  # @ is another way

tensor([[2.0659, 1.0448, 1.3915],
        [1.0448, 1.3847, 1.2229],
        [1.3915, 1.2229, 1.6603]], device='cuda:0')

## axis operations 

In [84]:
my_tensor

tensor([[0.0369, 0.7925, 0.9034, 0.7876],
        [0.9311, 0.3457, 0.5577, 0.2953],
        [0.6482, 0.9903, 0.2668, 0.4338]], device='cuda:0')

In [82]:
my_tensor.sum(axis=0) # columswise

tensor([1.6162, 2.1285, 1.7280, 1.5168], device='cuda:0')

In [85]:
my_tensor.sum(axis=1) # row-wise

tensor([2.5205, 2.1299, 2.3392], device='cuda:0')

In [91]:
my_tensor.max(axis=1) # row-wise

torch.return_types.max(values=tensor([0.9034, 0.9311, 0.9903], device='cuda:0'), indices=tensor([2, 0, 1], device='cuda:0'))

In [94]:
my_tensor.max(axis=1)[0], my_tensor.max(axis=1)[1] 
 # values,  indices

(tensor([0.9034, 0.9311, 0.9903], device='cuda:0'),
 tensor([2, 0, 1], device='cuda:0'))

In [89]:
my_tensor.argmax(axis=1) # row-wise

tensor([2, 0, 1], device='cuda:0')

In [87]:
my_tensor.max(axis=0) # column-wise

torch.return_types.max(values=tensor([0.9311, 0.9903, 0.9034, 0.7876], device='cuda:0'), indices=tensor([1, 2, 0, 0], device='cuda:0'))

## Concat

In [100]:
torch.cat([my_tensor, my_tensor], axis=1) # axis or dim , axis=1 means colum wise concat

tensor([[0.0369, 0.7925, 0.9034, 0.7876, 0.0369, 0.7925, 0.9034, 0.7876],
        [0.9311, 0.3457, 0.5577, 0.2953, 0.9311, 0.3457, 0.5577, 0.2953],
        [0.6482, 0.9903, 0.2668, 0.4338, 0.6482, 0.9903, 0.2668, 0.4338]],
       device='cuda:0')

In [102]:
torch.cat([my_tensor, my_tensor], dim=0) # axis=0 means row wise concat

tensor([[0.0369, 0.7925, 0.9034, 0.7876],
        [0.9311, 0.3457, 0.5577, 0.2953],
        [0.6482, 0.9903, 0.2668, 0.4338],
        [0.0369, 0.7925, 0.9034, 0.7876],
        [0.9311, 0.3457, 0.5577, 0.2953],
        [0.6482, 0.9903, 0.2668, 0.4338]], device='cuda:0')

## softmax

In [107]:
my_tensor

tensor([[0.0369, 0.7925, 0.9034, 0.7876],
        [0.9311, 0.3457, 0.5577, 0.2953],
        [0.6482, 0.9903, 0.2668, 0.4338]], device='cuda:0')

In [106]:
torch.nn.functional.softmax(my_tensor, dim=0) # sum of each column will be 1

tensor([[0.1891, 0.3498, 0.4471, 0.4323],
        [0.4624, 0.2238, 0.3164, 0.2642],
        [0.3485, 0.4264, 0.2365, 0.3035]], device='cuda:0')

In [112]:
print(0.1891+ 0.3498+ 0.4471+ 0.4323) # sum of row 1 != 1 
print(0.1891+ + 0.4624 + 0.3485) # sum of column 1  == 1   

1.4183
1.0


In [110]:
torch.nn.functional.softmax(my_tensor, dim=0).sum(axis=0)

tensor([1.0000, 1.0000, 1.0000, 1.0000], device='cuda:0')

In [108]:
torch.nn.functional.softmax(my_tensor, dim=1)

tensor([[0.1311, 0.2792, 0.3119, 0.2778],
        [0.3604, 0.2007, 0.2481, 0.1908],
        [0.2566, 0.3612, 0.1752, 0.2070]], device='cuda:0')

In [109]:
torch.nn.functional.softmax(my_tensor, dim=1).sum(axis=1)

tensor([1.0000, 1.0000, 1.0000], device='cuda:0')

# handling images

In [121]:
my_image = torch.rand(10, 3, 128, 128) # 10 images in a batch, 3 channels(RBG), Height, Width

In [122]:
np.round(my_image[1,0,:4,:4], 4)

tensor([[0.0588, 0.4991, 0.0245, 0.4091],
        [0.9752, 0.4800, 0.2861, 0.6377],
        [0.3820, 0.3939, 0.5672, 0.0297],
        [0.7492, 0.2333, 0.6376, 0.5377]])

In [123]:
my_image.size()

torch.Size([10, 3, 128, 128])

## CLipping

In [125]:
my_tensor

tensor([[0.0369, 0.7925, 0.9034, 0.7876],
        [0.9311, 0.3457, 0.5577, 0.2953],
        [0.6482, 0.9903, 0.2668, 0.4338]], device='cuda:0')

In [124]:
my_tensor.clip(0.2, 0.8)

tensor([[0.2000, 0.7925, 0.8000, 0.7876],
        [0.8000, 0.3457, 0.5577, 0.2953],
        [0.6482, 0.8000, 0.2668, 0.4338]], device='cuda:0')