<a href="https://colab.research.google.com/github/kuberiitb/learnings/blob/master/pytorch/lecture_02_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learnings from [Abhishek Thakur Pytoch Series](https://www.youtube.com/watch?v=_R-mvKBD5U8&list=PL98nY_tJQXZln8spB5uTZdKN08mYGkOf2&index=2)

In [131]:
import torch 

In [132]:
torch.cuda.is_available()

True

In [133]:
!nvidia-smi

Thu Feb  3 07:13:46 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P0    26W /  70W |   1332MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## autograd

In [135]:
a = torch.tensor([5.], requires_grad = True)
b = torch.tensor([6.], requires_grad = True)

In [136]:
a

tensor([5.], requires_grad=True)

In [137]:
b

tensor([6.], requires_grad=True)

In [138]:
y = a**3 - b**2

In [139]:
y

tensor([89.], grad_fn=<SubBackward0>)

In [141]:
# dy/da = 3 * a **2  = 2* 5**2 = 75
# dy/db = - 2 * b    = - 2 * 6 = -12  

In [145]:
print(a.grad)
print(b.grad) # None before computing 


None
None


In [148]:
y.backward() # computing grad wrt all variables

In [149]:
print(a.grad)
print(b.grad) # after computing 


tensor([75.])
tensor([-12.])


In [166]:
W = torch.randn(10,1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

In [167]:
W

tensor([[-0.8216],
        [ 2.2799],
        [ 0.3978],
        [-0.5996],
        [-0.2353],
        [ 0.2086],
        [-0.4670],
        [ 1.3343],
        [ 0.7608],
        [-1.7591]], requires_grad=True)

In [168]:
b

tensor([-0.8503], requires_grad=True)

In [169]:
x = torch.rand(1, 10) # grad not required

In [170]:
output = torch.matmul(x,W) + b 

In [171]:
loss = 1 - output

In [173]:
loss, output

(tensor([[0.0054]], grad_fn=<RsubBackward1>),
 tensor([[0.9946]], grad_fn=<AddBackward0>))

In [174]:
loss.backward()

In [175]:
W.grad

tensor([[-0.1145],
        [-0.5898],
        [-0.7862],
        [-0.3383],
        [-0.1791],
        [-0.7902],
        [-0.7081],
        [-0.5766],
        [-0.3006],
        [-0.1738]])

In [176]:
b.grad

tensor([-1.])

In [177]:
learning_rate = 0.01
with torch.no_grad():
  W = W - learning_rate * W.grad.data
  b = b - learning_rate * b.grad.data

In [178]:
W

tensor([[-0.8204],
        [ 2.2858],
        [ 0.4057],
        [-0.5963],
        [-0.2335],
        [ 0.2165],
        [-0.4599],
        [ 1.3400],
        [ 0.7638],
        [-1.7573]])

In [180]:
b # changed from -0.8503 to -0.84

tensor([-0.8403])

In [181]:
output = torch.matmul(x,W) + b 
loss = 1 - output

In [182]:
loss, output

(tensor([[-0.0316]]), tensor([[1.0316]]))